# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: t.r.shyam0007@gmail.com
author_name: Shyam
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_porsche_images
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: jupyterlab_porsche_images
repository: https://github.com/TRshyam/prosche
test: true
viewer_name: ''

